### ISSUE TITLE
line 20 error in script file

### ISSUE THREAD

**Issue by BedoEbied** [HassanElDesouky/SoundcloudLikesFetcher#1]
**I got this error:**

> Traceback (most recent call last):
>   File "script.py", line 20, in <module>
>     name = arr[1]
> IndexError: list index out of range
>

**Comment by HassanElDesouky** [comment]
Thank you for the feedback. I will solve the issue.

**Comment by HassanElDesouky** [comment]
It's fixed now. Kindly, view the updated Readme file.
